### ISSUE TITLE
feat: Release Action

### ISSUE THREAD

**Issue by zackha** [scottyzen/woonuxt#38]
Hi @scottyzen,

Using GitHub's release feature for your Woonuxt project can increase the number of views on your project's GitHub page. Therefore, it would be great to use releases in this project. You can follow the steps below for this.

## 1 - Generate Changelogs

We want the release we will make to automatically create a changelog, so we create a file path with the extension `.github/workflows` in the GitHub action and add a workflow file named `release.yml` inside.

```yml
# .github/workflows/release.yml

name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

It will be trigged whenever you push a tag to GitHub that starts with `v`.

This workflow file will save the following written commits as a changelog for the release.

    feat: { title: '🚀 Features' },
    fix: { title: '🐞 Bug Fixes' },
    perf: { title: '🏎 Performance' },

[👉 Changelog example](https://github.com/unocss/unocss/releases/tag/v0.39.0)

If you are using GitHub Actions and it's triggered by the correct event, the GITHUB_TOKEN will be generated automatically. If not you might go to /settings/actions to check your permission setting.

![image](https://user-images.githubusercontent.com/79358543/236145129-4a468a4c-9c91-4c4c-b422-c04260f2d8d7.png)

## 2 - Install `bumpp` 

```bash
npm install -g bumpp
```

Add the following script to the `package.json` file

```ts
"release": "bumpp --commit --push --tag"
```

and run.

```bash
npm run release
```

![Screenshot](https://jstools.dev/version-bump-prompt/img/screenshot.gif)

That's all for the processes.

Best Regards,
